'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from './provider';

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<head>
				<meta name='description' content='Generated by Ezequiel Rivas' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<meta charSet='utf-8' />
				<link rel='icon' href='/favicon.ico' />
			</head>
			<Providers>
				<body>{children}</body>
			</Providers>
		</html>
	);
}
